// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'description': string;
  'figure': string;
  'item': string;
}
export const cssExports: CssExports;
export default cssExports;
