// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'list': string;
  'section': string;
  'title': string;
  'titleDecor': string;
}
export const cssExports: CssExports;
export default cssExports;
