// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeIcon': string;
  'description': string;
  'modalInfo': string;
  'subTitle': string;
  'title': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
