// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'bannerItem': string;
  'bannerLink': string;
  'bannerTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
